In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('D:\Technocolabs\Task 1\default_of_credit_card_clients.xls')

In [4]:
import numpy as np

In [5]:
np.random.seed(seed=24)


In [6]:
random_integers = np.random.randint(low=1,high=5,size=100)
random_integers


array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [7]:
is_equal_to_3 = random_integers == 3


In [8]:
is_equal_to_3[:5]


array([ True, False, False, False, False])

In [9]:
sum(is_equal_to_3)


22

In [10]:
random_integers[is_equal_to_3]


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
id_counts = df['ID'].value_counts()
dupe_mask = id_counts == 2
dupe_mask[0:5]

05009844-7be8    True
b4937915-ad67    True
9878723a-0b58    True
d13465a5-a9e0    True
e39d23fe-aa5f    True
Name: ID, dtype: bool

In [12]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [13]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
11769  9878723a-0b58     130000    1          5         1   44     0      0   
11869  9878723a-0b58          0    0          0         0    0     0      0   
17604  05009844-7be8     180000    2          3         1   43    -1     -1   
17704  05009844-7be8          0    0          0         0    0     0      0   
17987  b4937915-ad67     240000    1          3         2   36     0      0   
18087  b4937915-ad67          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
11769      0      0  ...      54668      22780      13417      2452      2140   
11869      0      0  ...          0          0          0         0         0   
17604     -1     -1  ...        780          0          0         0       780   
17704      0      0  ...          0          0          0         0         0   
17987      0      0  ...      93057      55419      59336     10000     10000   
18087      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
11769      1093     13706       500       100                           1  
11869         0         0         0         0                           0  
17604       780         0         0         0                           0  
17704         0         0         0         0                           0  
17987     10000      5000      5000      5000                           0  
18087         0         0         0         0                           0  

[6 rows x 25 columns]

In [14]:
df_zero_mask = df == 0
df_zero_mask


ID  LIMIT_BAL    SEX  EDUCATION  MARRIAGE    AGE  PAY_1  PAY_2  \
0      False      False  False      False     False  False  False  False   
1      False      False  False      False     False  False  False  False   
2      False      False  False      False     False  False   True   True   
3      False      False  False      False     False  False   True   True   
4      False      False  False      False     False  False  False   True   
...      ...        ...    ...        ...       ...    ...    ...    ...   
29995  False      False  False      False     False  False   True   True   
29996  False      False  False      False     False  False  False  False   
29997  False      False  False      False     False  False  False  False   
29998  False      False  False      False     False  False  False  False   
29999  False      False  False      False     False  False   True   True   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0      False  False  ...       True       True       True      True     False   
1       True   True  ...      False      False      False      True     False   
2       True   True  ...      False      False      False     False     False   
3       True   True  ...      False      False      False     False     False   
4      False   True  ...      False      False      False     False     False   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29995   True   True  ...      False      False      False     False     False   
29996  False  False  ...      False      False       True     False     False   
29997  False  False  ...      False      False      False      True      True   
29998   True   True  ...      False      False      False     False     False   
29999   True   True  ...      False      False      False     False     False   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0          True      True      True      True                       False  
1         False     False      True     False                       False  
2         False     False     False     False                        True  
3         False     False     False     False                        True  
4         False     False     False     False                        True  
...         ...       ...       ...       ...                         ...  
29995     False     False     False     False                        True  
29996     False     False      True      True                        True  
29997     False     False     False     False                       False  
29998     False     False     False     False                       False  
29999     False     False     False     False                       False  

[30000 rows x 25 columns]

In [15]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)


315

In [22]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()


In [23]:
df_clean_1['ID'].nunique()


29685

In [24]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [25]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()


In [26]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2[['PAY_1', 'PAY_2']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PAY_1   26664 non-null  int64
 1   PAY_2   26664 non-null  int64
dtypes: int64(2)
memory usage: 624.9 KB


In [27]:
df_clean_2['EDUCATION'].replace(to_replace=[0, 5, 6], value=4, inplace=True)
df_clean_2['EDUCATION'].value_counts()

2    12458
1     9412
3     4380
4      414
Name: EDUCATION, dtype: int64

In [28]:
df_clean_2['MARRIAGE'].replace(to_replace=0, value=3, inplace=True)
df_clean_2['MARRIAGE'].value_counts()

2    14158
1    12172
3      334
Name: MARRIAGE, dtype: int64

In [29]:
df_clean_2['EDUCATION_CAT'] = 'none'


In [30]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)


EDUCATION EDUCATION_CAT
0          2          none
1          2          none
2          2          none
3          2          none
4          2          none
5          1          none
6          1          none
7          2          none
8          3          none
9          3          none

In [31]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [32]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION    EDUCATION_CAT
0          2       university
1          2       university
2          2       university
3          2       university
4          2       university
5          1  graduate school
6          1  graduate school
7          2       university
8          3      high school
9          3      high school

In [33]:
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)
df_with_ohe.to_csv('cleaned_data.csv', index=False)


In [55]:
df1=pd.read_csv('cleaned_data.csv')
df1

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24      2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2      85698822-43f5      90000    2          2         2   34      0      0   
3      0737c11b-be42      50000    2          2         1   37      0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57     -1      0   
...              ...        ...  ...        ...       ...  ...    ...    ...   
26659  ecff42d0-bdc6     220000    1          3         1   39      0      0   
26660  99d1fa0e-222b     150000    1          3         2   43     -1     -1   
26661  95cdd3e7-4f24      30000    1          2         2   37      4      3   
26662  00d03f02-04cd      80000    1          3         1   41      1     -1   
26663  15d69f9f-5ad3      50000    1          2         1   46      0      0   

       PAY_3  PAY_4  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         -1     -1  ...         0         0         0         0   
1          0      0  ...      1000      1000         0      2000   
2          0      0  ...      1000      1000      1000      5000   
3          0      0  ...      1200      1100      1069      1000   
4         -1      0  ...     10000      9000       689       679   
...      ...    ...  ...       ...       ...       ...       ...   
26659      0      0  ...      5003      3047      5000      1000   
26660     -1     -1  ...      8998       129         0         0   
26661      2     -1  ...     22000      4200      2000      3100   
26662      0      0  ...      1178      1926     52964      1804   
26663      0      0  ...      1430      1000      1000      1000   

       default payment next month  EDUCATION_CAT  graduate school  \
0                               1     university                0   
1                               1     university                0   
2                               0     university                0   
3                               0     university                0   
4                               0     university                0   
...                           ...            ...              ...   
26659                           0    high school                0   
26660                           0    high school                0   
26661                           1     university                0   
26662                           1    high school                0   
26663                           1     university                0   

       high school  others  university  
0                0       0           1  
1                0       0           1  
2                0       0           1  
3                0       0           1  
4                0       0           1  
...            ...     ...         ...  
26659            1       0           0  
26660            1       0           0  
26661            0       0           1  
26662            1       0           0  
26663            0       0           1  

[26664 rows x 30 columns]

In [84]:
df1.shape

(26664, 30)

In [92]:
C1 = df1.loc[:,'LIMIT_BAL':'PAY_AMT6']
C1.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -2  ...        689          0          0          0         0       689   
1      0  ...       2682       3272       3455       3261         0      1000   
2      0  ...      13559      14331      14948      15549      1518      1500   
3      0  ...      49291      28314      28959      29547      2000      2019   
4      0  ...      35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0         0         0         0  
1      1000      1000         0      2000  
2      1000      1000      1000      5000  
3      1200      1100      1069      1000  
4     10000      9000       689       679  

[5 rows x 23 columns]

In [99]:
C2 = df1.loc[:,'graduate school':'university']
C2

graduate school  high school  others  university
0                    0            0       0           1
1                    0            0       0           1
2                    0            0       0           1
3                    0            0       0           1
4                    0            0       0           1
...                ...          ...     ...         ...
26659                0            1       0           0
26660                0            1       0           0
26661                0            0       0           1
26662                0            1       0           0
26663                0            0       0           1

[26664 rows x 4 columns]

In [100]:
X= pd.concat([C1,C2],axis=1)
X

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0          20000    2          2         1   24      2      2     -1     -1   
1         120000    2          2         2   26     -1      2      0      0   
2          90000    2          2         2   34      0      0      0      0   
3          50000    2          2         1   37      0      0      0      0   
4          50000    1          2         1   57     -1      0     -1      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
26659     220000    1          3         1   39      0      0      0      0   
26660     150000    1          3         2   43     -1     -1     -1     -1   
26661      30000    1          2         2   37      4      3      2     -1   
26662      80000    1          3         1   41      1     -1      0      0   
26663      50000    1          2         1   46      0      0      0      0   

       PAY_5  ...  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         -2  ...         0       689         0         0         0         0   
1          0  ...         0      1000      1000      1000         0      2000   
2          0  ...      1518      1500      1000      1000      1000      5000   
3          0  ...      2000      2019      1200      1100      1069      1000   
4          0  ...      2000     36681     10000      9000       689       679   
...      ...  ...       ...       ...       ...       ...       ...       ...   
26659      0  ...      8500     20000      5003      3047      5000      1000   
26660      0  ...      1837      3526      8998       129         0         0   
26661      0  ...         0         0     22000      4200      2000      3100   
26662      0  ...     85900      3409      1178      1926     52964      1804   
26663      0  ...      2078      1800      1430      1000      1000      1000   

       graduate school  high school  others  university  
0                    0            0       0           1  
1                    0            0       0           1  
2                    0            0       0           1  
3                    0            0       0           1  
4                    0            0       0           1  
...                ...          ...     ...         ...  
26659                0            1       0           0  
26660                0            1       0           0  
26661                0            0       0           1  
26662                0            1       0           0  
26663                0            0       0           1  

[26664 rows x 27 columns]

In [135]:
y = df1['default payment next month'].values
y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [136]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [137]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [127]:
import matplotlib.pyplot as plt

In [ ]:
y_pred = regressor.predict(X_test)
df_pred = pd.DataFrame(y_pred.int(), columns =['predicted'] ) 
df_org = pd.DataFrame(y_test, columns =['Actual value'] ) 
df_pred

In [124]:
df_org = pd.DataFrame(y_test, columns =['Actual value'] ) 
df_org

Actual value
0                0
1                1
2                0
3                0
4                1
...            ...
5328             0
5329             0
5330             1
5331             0
5332             0

[5333 rows x 1 columns]

In [126]:
df3 = pd.concat([X_test,df_org,df_pred],axis=1)
df3

LIMIT_BAL  SEX  EDUCATION  MARRIAGE   AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0            NaN  NaN        NaN       NaN   NaN    NaN    NaN    NaN    NaN   
1            NaN  NaN        NaN       NaN   NaN    NaN    NaN    NaN    NaN   
2            NaN  NaN        NaN       NaN   NaN    NaN    NaN    NaN    NaN   
3            NaN  NaN        NaN       NaN   NaN    NaN    NaN    NaN    NaN   
4        50000.0  1.0        2.0       1.0  57.0   -1.0    0.0   -1.0    0.0   
...          ...  ...        ...       ...   ...    ...    ...    ...    ...   
26650   360000.0  1.0        1.0       2.0  35.0   -1.0   -1.0   -2.0   -2.0   
26652   250000.0  1.0        1.0       1.0  34.0    0.0    0.0    0.0    0.0   
26660   150000.0  1.0        3.0       2.0  43.0   -1.0   -1.0   -1.0   -1.0   
26662    80000.0  1.0        3.0       1.0  41.0    1.0   -1.0    0.0    0.0   
26663    50000.0  1.0        2.0       1.0  46.0    0.0    0.0    0.0    0.0   

       PAY_5  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  graduate school  \
0        NaN  ...       NaN       NaN       NaN       NaN              NaN   
1        NaN  ...       NaN       NaN       NaN       NaN              NaN   
2        NaN  ...       NaN       NaN       NaN       NaN              NaN   
3        NaN  ...       NaN       NaN       NaN       NaN              NaN   
4        0.0  ...   10000.0    9000.0     689.0     679.0              0.0   
...      ...  ...       ...       ...       ...       ...              ...   
26650   -2.0  ...       0.0       0.0       0.0       0.0              1.0   
26652    0.0  ...    9011.0    6000.0    7000.0    6009.0              1.0   
26660    0.0  ...    8998.0     129.0       0.0       0.0              0.0   
26662    0.0  ...    1178.0    1926.0   52964.0    1804.0              0.0   
26663    0.0  ...    1430.0    1000.0    1000.0    1000.0              0.0   

       high school  others  university  Actual value  predicted  
0              NaN     NaN         NaN           0.0   0.102200  
1              NaN     NaN         NaN           1.0  -0.069622  
2              NaN     NaN         NaN           0.0   0.231721  
3              NaN     NaN         NaN           0.0   0.127880  
4              0.0     0.0         1.0           1.0   0.476938  
...            ...     ...         ...           ...        ...  
26650          0.0     0.0         0.0           NaN        NaN  
26652          0.0     0.0         0.0           NaN        NaN  
26660          1.0     0.0         0.0           NaN        NaN  
26662          1.0     0.0         0.0           NaN        NaN  
26663          0.0     0.0         1.0           NaN        NaN  

[9633 rows x 29 columns]